# Generated by Django 4.1.2 on 2022-11-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_employee_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('company', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.IntegerField()),
            ],
        ),
    ]
