# Generated by Django 4.1.2 on 2022-11-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_project_alter_client_company_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='From_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='To_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default=(1997, 10, 19), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(default=1997, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='work_status',
            field=models.CharField(default=(1997, 10, 19), max_length=30),
            preserve_default=False,
        ),
    ]
